export const BOT_LOCALES = [
  "ar", "cs", "de", "en", "es", "fa", "fr", "hi", "id", "it", "ja", "ko", "ms", "nl", "pl",
  "pt", "pt-BR", "ru", "th", "tr", "uk", "uz", "vi", "zh-CN", "zh-TW",
] as const;

export type BotLocale = typeof BOT_LOCALES[number];

const ENGLISH = {
  settings: "Settings",
  contextCleared: "Context cleared.",
  maxImages: "Use at most 10 images. Please split the request; Mia did not discard any silently.",
  imageActionQuestion: "What would you like me to do with this image? I can analyze it, edit it, turn it into a sticker, or make a video.",
  analyzeImageButton: "Analyze image",
  editImageButton: "Edit image",
  stickerImageButton: "Make sticker",
  animateImageButton: "Make video",
  analyzeImagePrompt: "Reply with what you want to know about this image.",
  editImagePrompt: "Reply with how you want to change this image.",
  stickerImagePrompt: "Reply with how you want to turn this image into a sticker.",
  animateImagePrompt: "Reply with how you want the image to move.",
  mediaDisabled: "Media features are disabled in this group by an administrator.",
  modelUnavailable: "Your saved {capability} model is unavailable. Mia will use {model}.",
  noVisionModel: "No compatible vision model is available. Choose one in Mia settings.",
  queuedImage: "Queued image generation...",
  generatingNewImage: "Generating a new image...",
  activeLimit: "You already have 3 media jobs in progress.",
  requestAlready: "This request is already {status}.",
  videoMetadataMissing: "The selected video model has no complete Mia capability metadata. Choose a supported model.",
  unsupportedVideo: "Unsupported video parameters. This model supports 4-15 seconds, 768P, and 1:1 / 16:9 / 9:16.",
  actionUnavailable: "This action is unavailable.",
  videoQueuedShort: "Video queued",
  videoQueued: "Video queued. Mia will deliver it here when ready.",
  draftExpiredOrUsed: "This draft is expired or already used.",
  cancelled: "Cancelled",
  draftUnavailable: "Draft unavailable",
  videoDraftCancelled: "Video draft cancelled.",
  editInstruction: "Reply to the result with your edit instruction.",
  draftCreated: "Draft created",
  jobsAlreadyRunning: "3 media jobs are already running.",
  queued: "Queued",
  originalUnavailable: "The original file is unavailable.",
  sent: "Sent",
  downloadUnavailable: "Download unavailable.",
  adminOnly: "Only group administrators can change media settings.",
  mediaEnabled: "Mia media features are enabled.",
  mediaDisabledConfirmation: "Mia media features are disabled.",
  chatModelFallback: "The selected model {selected} is unavailable. Using {model} for this reply.",
  webSearchUnavailable: "I could not reach the live web search service this time. Please try again shortly.",
  videoDraftTitle: "Video draft (not charged)",
  modelLabel: "Model: {value}",
  modeLabel: "Mode: {value}",
  modeTextToVideo: "Text to video",
  modeImageToVideo: "Image to video",
  promptLabel: "Prompt: {value}",
  durationLabel: "Duration: {value} seconds",
  aspectRatioLabel: "Aspect ratio: {value}",
  resolutionLabel: "Resolution: {value}",
  channelDefaultResolution: "Channel default",
  videoResolutionConfirmationRequired: "This video's resolution needs to be confirmed again. Please send a new video request; omit the resolution to use the channel default.",
  videoSubmissionFailed: "The video request could not be submitted.",
  draftExpires: "Expires in 10 minutes.",
  ratioButton: "Ratio",
  generateVideoButton: "Generate video",
  cancelButton: "Cancel",
  clarificationImage: "Please send or reply to the image you want to use.",
  clarificationQuestion: "What would you like to know about the image?",
  clarificationInstruction: "What should Mia create or change?",
  tooManyImages: "Use at most 10 images.",
  fileTooLarge: "Each image must be 10 MB or smaller.",
  totalTooLarge: "The images must total 30 MB or less. Please split the request.",
  unsupportedImage: "One of the files is not a supported image.",
  telegramNotBound: "Connect this Telegram account to APIMaster first, then try again.",
  accountDisabled: "This APIMaster account is currently unavailable. Check the account status first.",
  noUsableKey: "Your APIMaster account has no API Key available for {model}.",
  selectedModelUnavailable: "The selected model is temporarily unavailable. Try again later or choose another model in Mia settings.",
  quotaUnavailable: "This request could not be completed. Check your APIMaster quota and try again.",
  mediaBindRequired: "Images and videos require an APIMaster account. Sign up or sign in, then connect this Telegram account.",
  mediaTokenRequired: "Images and videos require your own APIMaster API Token. Create a Token first.",
  mediaTopUpRequired: "Your APIMaster balance is insufficient for this media request. Add funds and try again.",
  registerAndBindButton: "Sign up and connect",
  telegramCreateOrLoginButton: "Create or sign in with Telegram",
  telegramBindExistingButton: "I already have an APIMaster account",
  createTokenButton: "Create API Token",
  topUpButton: "Add funds",
  serviceUnavailable: "The service is temporarily unavailable. Please try again later.",
  temporaryError: "A temporary error occurred. Mia is still processing and will check again.",
  videoDraftExpired: "This video draft expired.",
  mediaTimedOut: "This media task timed out.",
  submissionUnknown: "The request outcome could not be confirmed, so Mia did not submit it again.",
  submitted: "Submitted. Mia will deliver the result here when it is ready.",
  submissionFailed: "The media request still could not be submitted after one automatic retry.",
  generationFailed: "Media generation failed.",
  stillProcessing: "Still processing{progress}...",
  videoReadyLink: "Video ready: {url}",
  generateAgain: "Generate again",
  generateAnother: "Generate another",
  continueEditing: "Continue editing",
  downloadOriginal: "Download original",
  share: "Share on X",
  videoReady: "Video ready",
  imageReady: "Image ready",
  stickerPrivateOnly: "Sticker creation is currently available in a private chat with Mia only.",
  stickerSingleImage: "Send one image at a time to create a sticker.",
  addStickerPack: "Add sticker pack",
  translationModeEnabled: "Translation: {pair}",
  translationModeDisabled: "Translation mode is off.",
  translationModeExpired: "Translation mode expired after 30 minutes.",
  translationSwitchButton: "Switch languages",
  translationExitButton: "Exit translation",
  translationCopyButton: "Copy",
  translationChoosePair: "Choose a language pair:",
  translationChooseLeftLanguage: "Choose the left language:",
  translationChooseRightLanguage: "Choose the right language:",
  translationPreviousButton: "Previous",
  translationNextButton: "Next",
  translationBackButton: "Back",
  translationPrivateOnly: "Translation mode is available in private chat only.",
  telegramLoginConfirmed: "Telegram is confirmed. Tap below to sign in to APIMaster.",
  telegramLoginButton: "Log in now",
  telegramLoginExpired: "This login link expired. Return to APIMaster and try again.",
  telegramLoginUnavailable: "Login confirmation is temporarily unavailable. Please try again shortly.",
} as const;

export type BotMessageKey = keyof typeof ENGLISH;
type MessageOverrides = Partial<Record<BotMessageKey, string>>;

const CHINESE_SIMPLIFIED: MessageOverrides = {
  settings: "设置",
  contextCleared: "上下文已清除。",
  maxImages: "一次最多使用 10 张图片，请拆分后重试；Mia 不会静默丢弃图片。",
  imageActionQuestion: "这张图想让我做什么？我可以帮你看图、修改图片、做成贴纸或视频。",
  analyzeImageButton: "看懂这张图",
  editImageButton: "修改图片",
  stickerImageButton: "做成贴纸",
  animateImageButton: "做成视频",
  analyzeImagePrompt: "回复这条消息，告诉我你想了解图片中的什么。",
  editImagePrompt: "回复这条消息，告诉我你想怎样修改图片。",
  stickerImagePrompt: "回复这条消息，告诉我想把这张图做成什么样的贴纸。",
  animateImagePrompt: "回复这条消息，告诉我你希望画面怎样动起来。",
  mediaDisabled: "管理员已关闭本群的媒体功能。",
  modelUnavailable: "你保存的{capability}模型不可用，Mia 将改用 {model}。",
  noVisionModel: "目前没有兼容的视觉模型，请在 Mia 设置中选择一个。",
  queuedImage: "图片生成任务已排队……",
  generatingNewImage: "正在生成新图片……",
  activeLimit: "你已经有 3 个媒体任务正在处理。",
  requestAlready: "这个请求已处于“{status}”状态。",
  videoMetadataMissing: "所选视频模型缺少完整的 Mia 能力信息，请选择受支持的模型。",
  unsupportedVideo: "视频参数不受支持。此模型支持 4–15 秒、768P，以及 1:1、16:9、9:16 画幅。",
  actionUnavailable: "这个操作不可用。",
  videoQueuedShort: "视频已排队",
  videoQueued: "视频任务已排队，完成后 Mia 会发送到这里。",
  draftExpiredOrUsed: "这个草稿已过期或已经使用。",
  cancelled: "已取消",
  draftUnavailable: "草稿不可用",
  videoDraftCancelled: "视频草稿已取消。",
  editInstruction: "请回复生成结果，并说明你想如何修改。",
  draftCreated: "草稿已创建",
  jobsAlreadyRunning: "已有 3 个媒体任务正在处理。",
  queued: "已排队",
  originalUnavailable: "原始文件不可用。",
  sent: "已发送",
  downloadUnavailable: "暂时无法下载。",
  adminOnly: "只有群管理员可以更改媒体设置。",
  mediaEnabled: "Mia 媒体功能已开启。",
  mediaDisabledConfirmation: "Mia 媒体功能已关闭。",
  chatModelFallback: "所选模型 {selected} 不可用，本次回复将使用 {model}。",
  webSearchUnavailable: "这次没能连上实时联网搜索，请稍后再试。",
  videoDraftTitle: "视频生成草稿（尚未扣费）",
  modelLabel: "模型：{value}",
  modeLabel: "模式：{value}",
  modeTextToVideo: "文生视频",
  modeImageToVideo: "图生视频",
  promptLabel: "提示词：{value}",
  durationLabel: "时长：{value} 秒",
  aspectRatioLabel: "画幅：{value}",
  resolutionLabel: "清晰度：{value}",
  channelDefaultResolution: "渠道默认",
  videoResolutionConfirmationRequired: "此视频任务的分辨率需要重新确认。请重新发送视频请求，不指定分辨率时使用渠道默认值。",
  videoSubmissionFailed: "视频请求提交失败。",
  draftExpires: "草稿将在 10 分钟后过期。",
  ratioButton: "切换画幅",
  generateVideoButton: "生成视频",
  cancelButton: "取消",
  clarificationImage: "请发送或回复你想使用的图片。",
  clarificationQuestion: "你想了解图片中的什么内容？",
  clarificationInstruction: "你想让 Mia 创建或修改什么？",
  tooManyImages: "一次最多使用 10 张图片。",
  fileTooLarge: "每张图片不能超过 10 MB。",
  totalTooLarge: "图片总大小不能超过 30 MB，请拆分后重试。",
  unsupportedImage: "其中一个文件不是受支持的图片。",
  telegramNotBound: "请先在 APIMaster 绑定这个 Telegram 账号，然后再试。",
  accountDisabled: "这个 APIMaster 账号目前不可用，请先检查账号状态。",
  noUsableKey: "你的 APIMaster 账号目前没有可用于 {model} 的 API Key。",
  selectedModelUnavailable: "当前选择的模型暂不可用，请稍后重试或在 Mia 设置中更换模型。",
  quotaUnavailable: "本次请求暂时无法完成，请检查 APIMaster 额度后再试。",
  mediaBindRequired: "图片和视频需要 APIMaster 账号，请先注册或登录并绑定这个 Telegram 账号。",
  mediaTokenRequired: "图片和视频需要使用你自己的 APIMaster API Token，请先创建 Token。",
  mediaTopUpRequired: "你的 APIMaster 余额不足以完成本次媒体请求，请充值后重试。",
  registerAndBindButton: "注册并绑定",
  telegramCreateOrLoginButton: "用 Telegram 创建/登录",
  telegramBindExistingButton: "我已有 APIMaster 账号",
  createTokenButton: "创建 API Token",
  topUpButton: "去充值",
  serviceUnavailable: "服务暂时不可用，请稍后再试。",
  temporaryError: "发生了临时错误，Mia 仍在处理，稍后会再次检查。",
  videoDraftExpired: "这个视频草稿已过期。",
  mediaTimedOut: "媒体任务处理超时。",
  submissionUnknown: "无法确认上游是否收到请求。为避免重复扣费，Mia 没有再次提交。",
  submitted: "已提交，生成完成后 Mia 会把结果发送到这里。",
  submissionFailed: "媒体请求自动重试一次后仍然提交失败。",
  generationFailed: "媒体生成失败。",
  stillProcessing: "仍在处理中{progress}……",
  videoReadyLink: "视频已生成：{url}",
  generateAgain: "再次生成",
  generateAnother: "再生成一张",
  continueEditing: "继续修改",
  downloadOriginal: "下载原图",
  share: "分享到 X",
  videoReady: "视频已生成",
  imageReady: "图片已生成",
  stickerPrivateOnly: "贴纸生成功能目前只支持和 Mia 私聊。",
  stickerSingleImage: "一次请只发一张图片来制作贴纸。",
  addStickerPack: "添加贴纸包",
  translationModeEnabled: "翻译：{pair}",
  translationModeDisabled: "翻译模式已退出。",
  translationModeExpired: "翻译模式已因 30 分钟无操作自动退出。",
  translationSwitchButton: "切换语言",
  translationExitButton: "退出翻译",
  translationCopyButton: "复制",
  translationChoosePair: "选择语言对：",
  translationChooseLeftLanguage: "选择左侧语言：",
  translationChooseRightLanguage: "选择右侧语言：",
  translationPreviousButton: "上一页",
  translationNextButton: "下一页",
  translationBackButton: "返回",
  translationPrivateOnly: "翻译模式仅支持私聊。",
  telegramLoginConfirmed: "💳 登录 APIMaster\n🌈 马上开始 AI 之旅 ⚡️⚡️⚡️\n👇 点击按钮，马上登录",
  telegramLoginButton: "登录 APIMaster",
  telegramLoginExpired: "这个登录链接已过期，请返回 APIMaster 后重试。",
  telegramLoginUnavailable: "登录确认暂时不可用，请稍后重试。",
};

const CHINESE_TRADITIONAL: MessageOverrides = {
  ...CHINESE_SIMPLIFIED,
  settings: "設定",
  contextCleared: "對話內容已清除。",
  queuedImage: "圖片生成任務已排隊……",
  generatingNewImage: "正在生成新圖片……",
  submitted: "已提交，生成完成後 Mia 會把結果傳送到這裡。",
  stillProcessing: "仍在處理中{progress}……",
  imageReady: "圖片已生成",
  stickerPrivateOnly: "貼紙生成功能目前只支援與 Mia 私聊。",
  stickerSingleImage: "一次請只傳送一張圖片來製作貼紙。",
  addStickerPack: "加入貼紙包",
  videoReady: "影片已生成",
  generateAgain: "再次生成",
  generateAnother: "再生成一張",
  continueEditing: "繼續修改",
  downloadOriginal: "下載原圖",
  share: "分享到 X",
  ratioButton: "切換畫幅",
  generateVideoButton: "生成影片",
  cancelButton: "取消",
  mediaBindRequired: "圖片和影片需要 APIMaster 帳號，請先註冊或登入並綁定這個 Telegram 帳號。",
  mediaTokenRequired: "圖片和影片需要使用你自己的 APIMaster API Token，請先建立 Token。",
  mediaTopUpRequired: "你的 APIMaster 餘額不足以完成這次媒體請求，請儲值後再試。",
  registerAndBindButton: "註冊並綁定",
  telegramCreateOrLoginButton: "用 Telegram 建立/登入",
  telegramBindExistingButton: "我已有 APIMaster 帳號",
  createTokenButton: "建立 API Token",
  selectedModelUnavailable: "目前選擇的模型暫時不可用，請稍後再試或在 Mia 設定中更換模型。",
  topUpButton: "去儲值",
};

// Core asynchronous media copy is localized for every language offered by the Mini App.
// Less common administrative and validation copy falls back to English unless overridden.
const CORE_TRANSLATIONS: Record<Exclude<BotLocale, "en" | "zh-CN" | "zh-TW">, MessageOverrides> = {
  ar: { queuedImage: "تمت إضافة مهمة إنشاء الصورة إلى قائمة الانتظار…", submitted: "تم الإرسال. سترسل Mia النتيجة هنا عندما تصبح جاهزة.", imageReady: "الصورة جاهزة", videoReady: "الفيديو جاهز", generateAgain: "إنشاء مرة أخرى", generateAnother: "إنشاء صورة أخرى", continueEditing: "متابعة التعديل", downloadOriginal: "تنزيل الأصل", share: "مشاركة", stillProcessing: "لا تزال المعالجة جارية{progress}…", generationFailed: "فشل إنشاء الوسائط.", temporaryError: "حدث خطأ مؤقت. لا تزال Mia تعالج الطلب وستتحقق مرة أخرى.", activeLimit: "لديك بالفعل 3 مهام وسائط قيد التنفيذ." },
  cs: { queuedImage: "Generování obrázku bylo zařazeno do fronty…", submitted: "Odesláno. Mia sem výsledek po dokončení doručí.", imageReady: "Obrázek je připraven", videoReady: "Video je připraveno", generateAgain: "Generovat znovu", generateAnother: "Generovat další", continueEditing: "Pokračovat v úpravách", downloadOriginal: "Stáhnout originál", share: "Sdílet", stillProcessing: "Stále se zpracovává{progress}…", generationFailed: "Generování médií selhalo.", temporaryError: "Došlo k dočasné chybě. Mia požadavek stále zpracovává a zkusí to znovu.", activeLimit: "Již máte 3 probíhající mediální úlohy." },
  de: { queuedImage: "Bildgenerierung wurde eingereiht…", submitted: "Übermittelt. Mia sendet das Ergebnis hierher, sobald es fertig ist.", imageReady: "Bild ist fertig", videoReady: "Video ist fertig", generateAgain: "Erneut generieren", generateAnother: "Weiteres generieren", continueEditing: "Weiter bearbeiten", downloadOriginal: "Original herunterladen", share: "Teilen", stillProcessing: "Wird noch verarbeitet{progress}…", generationFailed: "Mediengenerierung fehlgeschlagen.", temporaryError: "Ein vorübergehender Fehler ist aufgetreten. Mia verarbeitet weiter und prüft erneut.", activeLimit: "Du hast bereits 3 laufende Medienaufträge." },
  es: { queuedImage: "Generación de imagen en cola…", submitted: "Enviado. Mia publicará el resultado aquí cuando esté listo.", imageReady: "Imagen lista", videoReady: "Vídeo listo", generateAgain: "Generar de nuevo", generateAnother: "Generar otra", continueEditing: "Seguir editando", downloadOriginal: "Descargar original", share: "Compartir", stillProcessing: "Aún procesando{progress}…", generationFailed: "Falló la generación del contenido.", temporaryError: "Se produjo un error temporal. Mia sigue procesando y volverá a comprobarlo.", activeLimit: "Ya tienes 3 tareas multimedia en curso." },
  fa: { queuedImage: "درخواست ساخت تصویر در صف قرار گرفت…", submitted: "ارسال شد. Mia پس از آماده شدن نتیجه را اینجا می‌فرستد.", imageReady: "تصویر آماده است", videoReady: "ویدیو آماده است", generateAgain: "ساخت دوباره", generateAnother: "ساخت تصویر دیگر", continueEditing: "ادامه ویرایش", downloadOriginal: "دانلود نسخه اصلی", share: "اشتراک‌گذاری", stillProcessing: "همچنان در حال پردازش{progress}…", generationFailed: "ساخت رسانه ناموفق بود.", temporaryError: "خطای موقتی رخ داد. Mia همچنان در حال پردازش است و دوباره بررسی می‌کند.", activeLimit: "در حال حاضر ۳ کار رسانه‌ای در حال اجرا دارید." },
  fr: { queuedImage: "Génération de l’image mise en attente…", submitted: "Envoyé. Mia publiera le résultat ici dès qu’il sera prêt.", imageReady: "Image prête", videoReady: "Vidéo prête", generateAgain: "Générer à nouveau", generateAnother: "Générer une autre", continueEditing: "Continuer les modifications", downloadOriginal: "Télécharger l’original", share: "Partager", stillProcessing: "Traitement en cours{progress}…", generationFailed: "La génération du média a échoué.", temporaryError: "Une erreur temporaire est survenue. Mia poursuit le traitement et vérifiera à nouveau.", activeLimit: "Vous avez déjà 3 tâches multimédias en cours." },
  hi: { queuedImage: "इमेज जनरेशन कतार में जोड़ दिया गया है…", submitted: "सबमिट हो गया। तैयार होने पर Mia परिणाम यहीं भेजेगी।", imageReady: "इमेज तैयार है", videoReady: "वीडियो तैयार है", generateAgain: "फिर से बनाएँ", generateAnother: "एक और बनाएँ", continueEditing: "संपादन जारी रखें", downloadOriginal: "मूल डाउनलोड करें", share: "शेयर करें", stillProcessing: "अभी प्रोसेस हो रहा है{progress}…", generationFailed: "मीडिया जनरेशन विफल रहा।", temporaryError: "एक अस्थायी त्रुटि हुई। Mia अभी भी प्रोसेस कर रही है और फिर जाँच करेगी।", activeLimit: "आपके 3 मीडिया कार्य पहले से चल रहे हैं।" },
  id: { queuedImage: "Pembuatan gambar masuk antrean…", submitted: "Terkirim. Mia akan mengirim hasilnya ke sini setelah siap.", imageReady: "Gambar siap", videoReady: "Video siap", generateAgain: "Buat lagi", generateAnother: "Buat gambar lain", continueEditing: "Lanjutkan pengeditan", downloadOriginal: "Unduh versi asli", share: "Bagikan", stillProcessing: "Masih diproses{progress}…", generationFailed: "Pembuatan media gagal.", temporaryError: "Terjadi kesalahan sementara. Mia masih memproses dan akan memeriksa lagi.", activeLimit: "Anda sudah memiliki 3 tugas media yang sedang berjalan." },
  it: { queuedImage: "Generazione dell’immagine in coda…", submitted: "Inviato. Mia pubblicherà qui il risultato quando sarà pronto.", imageReady: "Immagine pronta", videoReady: "Video pronto", generateAgain: "Genera di nuovo", generateAnother: "Generane un’altra", continueEditing: "Continua a modificare", downloadOriginal: "Scarica originale", share: "Condividi", stillProcessing: "Elaborazione in corso{progress}…", generationFailed: "Generazione dei contenuti non riuscita.", temporaryError: "Si è verificato un errore temporaneo. Mia continua l’elaborazione e verificherà di nuovo.", activeLimit: "Hai già 3 attività multimediali in corso." },
  ja: { queuedImage: "画像生成をキューに追加しました…", submitted: "送信しました。完了すると Mia がここに結果を送ります。", imageReady: "画像が完成しました", videoReady: "動画が完成しました", generateAgain: "もう一度生成", generateAnother: "もう1枚生成", continueEditing: "編集を続ける", downloadOriginal: "元データをダウンロード", share: "共有", stillProcessing: "処理中です{progress}…", generationFailed: "メディアの生成に失敗しました。", temporaryError: "一時的なエラーが発生しました。Mia は処理を続け、再度確認します。", activeLimit: "すでに3件のメディアタスクが処理中です。" },
  ko: { queuedImage: "이미지 생성 작업이 대기열에 추가되었습니다…", submitted: "제출되었습니다. 완료되면 Mia가 여기에 결과를 보냅니다.", imageReady: "이미지가 준비되었습니다", videoReady: "동영상이 준비되었습니다", generateAgain: "다시 생성", generateAnother: "하나 더 생성", continueEditing: "계속 편집", downloadOriginal: "원본 다운로드", share: "공유", stillProcessing: "처리 중입니다{progress}…", generationFailed: "미디어 생성에 실패했습니다.", temporaryError: "일시적인 오류가 발생했습니다. Mia가 계속 처리하고 다시 확인합니다.", activeLimit: "이미 3개의 미디어 작업이 진행 중입니다." },
  ms: { queuedImage: "Penjanaan imej dimasukkan dalam baris gilir…", submitted: "Telah dihantar. Mia akan menghantar hasil di sini apabila siap.", imageReady: "Imej sedia", videoReady: "Video sedia", generateAgain: "Jana semula", generateAnother: "Jana satu lagi", continueEditing: "Teruskan mengedit", downloadOriginal: "Muat turun asal", share: "Kongsi", stillProcessing: "Masih diproses{progress}…", generationFailed: "Penjanaan media gagal.", temporaryError: "Ralat sementara berlaku. Mia masih memproses dan akan menyemak semula.", activeLimit: "Anda sudah mempunyai 3 tugas media yang sedang berjalan." },
  nl: { queuedImage: "Afbeelding genereren staat in de wachtrij…", submitted: "Verzonden. Mia plaatst het resultaat hier zodra het klaar is.", imageReady: "Afbeelding is klaar", videoReady: "Video is klaar", generateAgain: "Opnieuw genereren", generateAnother: "Nog een genereren", continueEditing: "Verder bewerken", downloadOriginal: "Origineel downloaden", share: "Delen", stillProcessing: "Nog bezig{progress}…", generationFailed: "Media genereren is mislukt.", temporaryError: "Er is een tijdelijke fout opgetreden. Mia verwerkt de taak nog en controleert opnieuw.", activeLimit: "Je hebt al 3 mediataken in uitvoering." },
  pl: { queuedImage: "Generowanie obrazu dodano do kolejki…", submitted: "Wysłano. Mia dostarczy wynik tutaj, gdy będzie gotowy.", imageReady: "Obraz jest gotowy", videoReady: "Film jest gotowy", generateAgain: "Wygeneruj ponownie", generateAnother: "Wygeneruj kolejny", continueEditing: "Kontynuuj edycję", downloadOriginal: "Pobierz oryginał", share: "Udostępnij", stillProcessing: "Nadal przetwarzam{progress}…", generationFailed: "Generowanie multimediów nie powiodło się.", temporaryError: "Wystąpił tymczasowy błąd. Mia nadal przetwarza zadanie i sprawdzi ponownie.", activeLimit: "Masz już 3 trwające zadania multimedialne." },
  pt: { queuedImage: "Geração de imagem adicionada à fila…", submitted: "Enviado. A Mia publicará o resultado aqui quando estiver pronto.", imageReady: "Imagem pronta", videoReady: "Vídeo pronto", generateAgain: "Gerar novamente", generateAnother: "Gerar outra", continueEditing: "Continuar a editar", downloadOriginal: "Descarregar original", share: "Partilhar", stillProcessing: "Ainda a processar{progress}…", generationFailed: "A geração de multimédia falhou.", temporaryError: "Ocorreu um erro temporário. A Mia continua a processar e verificará novamente.", activeLimit: "Já tem 3 tarefas multimédia em curso." },
  "pt-BR": { queuedImage: "Geração de imagem adicionada à fila…", submitted: "Enviado. A Mia publicará o resultado aqui quando estiver pronto.", imageReady: "Imagem pronta", videoReady: "Vídeo pronto", generateAgain: "Gerar novamente", generateAnother: "Gerar outra", continueEditing: "Continuar editando", downloadOriginal: "Baixar original", share: "Compartilhar", stillProcessing: "Ainda processando{progress}…", generationFailed: "A geração de mídia falhou.", temporaryError: "Ocorreu um erro temporário. A Mia continua processando e verificará novamente.", activeLimit: "Você já tem 3 tarefas de mídia em andamento." },
  ru: { queuedImage: "Генерация изображения поставлена в очередь…", submitted: "Отправлено. Mia пришлёт результат сюда, когда он будет готов.", imageReady: "Изображение готово", videoReady: "Видео готово", generateAgain: "Создать снова", generateAnother: "Создать ещё", continueEditing: "Продолжить редактирование", downloadOriginal: "Скачать оригинал", share: "Поделиться", stillProcessing: "Обработка продолжается{progress}…", generationFailed: "Не удалось создать медиафайл.", temporaryError: "Произошла временная ошибка. Mia продолжает обработку и проверит ещё раз.", activeLimit: "У вас уже выполняются 3 медиазадачи." },
  th: { queuedImage: "เพิ่มงานสร้างรูปภาพลงในคิวแล้ว…", submitted: "ส่งแล้ว Mia จะส่งผลลัพธ์ที่นี่เมื่อพร้อม", imageReady: "รูปภาพพร้อมแล้ว", videoReady: "วิดีโอพร้อมแล้ว", generateAgain: "สร้างอีกครั้ง", generateAnother: "สร้างเพิ่ม", continueEditing: "แก้ไขต่อ", downloadOriginal: "ดาวน์โหลดต้นฉบับ", share: "แชร์", stillProcessing: "กำลังประมวลผล{progress}…", generationFailed: "สร้างสื่อไม่สำเร็จ", temporaryError: "เกิดข้อผิดพลาดชั่วคราว Mia ยังประมวลผลอยู่และจะตรวจสอบอีกครั้ง", activeLimit: "คุณมีงานสื่อที่กำลังดำเนินการอยู่แล้ว 3 งาน" },
  tr: { queuedImage: "Görsel oluşturma sıraya alındı…", submitted: "Gönderildi. Hazır olduğunda Mia sonucu buraya iletecek.", imageReady: "Görsel hazır", videoReady: "Video hazır", generateAgain: "Yeniden oluştur", generateAnother: "Bir tane daha oluştur", continueEditing: "Düzenlemeye devam et", downloadOriginal: "Orijinali indir", share: "Paylaş", stillProcessing: "İşlenmeye devam ediyor{progress}…", generationFailed: "Medya oluşturulamadı.", temporaryError: "Geçici bir hata oluştu. Mia işlemeye devam ediyor ve tekrar kontrol edecek.", activeLimit: "Zaten devam eden 3 medya göreviniz var." },
  uk: { queuedImage: "Створення зображення додано до черги…", submitted: "Надіслано. Mia доставить результат сюди, коли він буде готовий.", imageReady: "Зображення готове", videoReady: "Відео готове", generateAgain: "Створити знову", generateAnother: "Створити ще", continueEditing: "Продовжити редагування", downloadOriginal: "Завантажити оригінал", share: "Поділитися", stillProcessing: "Обробка триває{progress}…", generationFailed: "Не вдалося створити медіафайл.", temporaryError: "Сталася тимчасова помилка. Mia продовжує обробку й перевірить ще раз.", activeLimit: "У вас уже виконується 3 медіазавдання." },
  uz: { queuedImage: "Rasm yaratish navbatga qo‘shildi…", submitted: "Yuborildi. Tayyor bo‘lgach, Mia natijani shu yerga jo‘natadi.", imageReady: "Rasm tayyor", videoReady: "Video tayyor", generateAgain: "Qayta yaratish", generateAnother: "Yana birini yaratish", continueEditing: "Tahrirlashni davom ettirish", downloadOriginal: "Aslini yuklab olish", share: "Ulashish", stillProcessing: "Hali qayta ishlanmoqda{progress}…", generationFailed: "Media yaratilmadi.", temporaryError: "Vaqtinchalik xato yuz berdi. Mia ishlov berishni davom ettirib, yana tekshiradi.", activeLimit: "Sizda allaqachon 3 ta media vazifa bajarilmoqda." },
  vi: { queuedImage: "Đã đưa tác vụ tạo ảnh vào hàng đợi…", submitted: "Đã gửi. Mia sẽ gửi kết quả tại đây khi hoàn tất.", imageReady: "Ảnh đã sẵn sàng", videoReady: "Video đã sẵn sàng", generateAgain: "Tạo lại", generateAnother: "Tạo thêm ảnh", continueEditing: "Tiếp tục chỉnh sửa", downloadOriginal: "Tải bản gốc", share: "Chia sẻ", stillProcessing: "Vẫn đang xử lý{progress}…", generationFailed: "Tạo nội dung đa phương tiện thất bại.", temporaryError: "Đã xảy ra lỗi tạm thời. Mia vẫn đang xử lý và sẽ kiểm tra lại.", activeLimit: "Bạn đã có 3 tác vụ đa phương tiện đang chạy." },
};

const SETTINGS_TRANSLATIONS: Record<Exclude<BotLocale, "en" | "zh-CN" | "zh-TW">, string> = {
  ar: "الإعدادات",
  cs: "Nastavení",
  de: "Einstellungen",
  es: "Ajustes",
  fa: "تنظیمات",
  fr: "Réglages",
  hi: "सेटिंग्स",
  id: "Pengaturan",
  it: "Impostazioni",
  ja: "設定",
  ko: "설정",
  ms: "Tetapan",
  nl: "Instellingen",
  pl: "Ustawienia",
  pt: "Definições",
  "pt-BR": "Configurações",
  ru: "Настройки",
  th: "การตั้งค่า",
  tr: "Ayarlar",
  uk: "Налаштування",
  uz: "Sozlamalar",
  vi: "Cài đặt",
};

type AccessMessageKey = "mediaBindRequired" | "mediaTokenRequired" | "mediaTopUpRequired" |
  "registerAndBindButton" | "createTokenButton" | "topUpButton";

const ACCESS_TRANSLATIONS: Record<Exclude<BotLocale, "en" | "zh-CN" | "zh-TW">, Record<AccessMessageKey, string>> = {
  ar: { mediaBindRequired: "تتطلب الصور ومقاطع الفيديو حساب APIMaster. سجّل أو ادخل ثم اربط حساب Telegram.", mediaTokenRequired: "تتطلب الصور ومقاطع الفيديو رمز APIMaster API خاصًا بك. أنشئ رمزًا أولًا.", mediaTopUpRequired: "رصيد APIMaster غير كافٍ لهذا الطلب. أضف رصيدًا وحاول مجددًا.", registerAndBindButton: "التسجيل والربط", createTokenButton: "إنشاء رمز API", topUpButton: "إضافة رصيد" },
  cs: { mediaBindRequired: "Obrázky a videa vyžadují účet APIMaster. Přihlaste se a propojte Telegram.", mediaTokenRequired: "Obrázky a videa vyžadují vlastní APIMaster API Token. Nejprve jej vytvořte.", mediaTopUpRequired: "Zůstatek APIMaster nestačí. Doplňte prostředky a zkuste to znovu.", registerAndBindButton: "Registrovat a propojit", createTokenButton: "Vytvořit API Token", topUpButton: "Dobít kredit" },
  de: { mediaBindRequired: "Für Bilder und Videos ist ein APIMaster-Konto erforderlich. Melde dich an und verbinde Telegram.", mediaTokenRequired: "Für Bilder und Videos brauchst du einen eigenen APIMaster API-Token. Erstelle zuerst einen Token.", mediaTopUpRequired: "Dein APIMaster-Guthaben reicht nicht aus. Lade Guthaben auf und versuche es erneut.", registerAndBindButton: "Registrieren und verbinden", createTokenButton: "API-Token erstellen", topUpButton: "Guthaben aufladen" },
  es: { mediaBindRequired: "Las imágenes y los vídeos requieren una cuenta de APIMaster. Regístrate o inicia sesión y vincula Telegram.", mediaTokenRequired: "Las imágenes y los vídeos requieren tu propio Token de API de APIMaster. Crea uno primero.", mediaTopUpRequired: "Tu saldo de APIMaster no es suficiente. Añade fondos e inténtalo de nuevo.", registerAndBindButton: "Registrarse y vincular", createTokenButton: "Crear Token de API", topUpButton: "Añadir fondos" },
  fa: { mediaBindRequired: "تصویر و ویدیو به حساب APIMaster نیاز دارند. ثبت‌نام یا وارد شوید و تلگرام را متصل کنید.", mediaTokenRequired: "تصویر و ویدیو به توکن API شخصی APIMaster نیاز دارند. ابتدا توکن بسازید.", mediaTopUpRequired: "موجودی APIMaster کافی نیست. حساب را شارژ و دوباره تلاش کنید.", registerAndBindButton: "ثبت‌نام و اتصال", createTokenButton: "ساخت توکن API", topUpButton: "افزایش موجودی" },
  fr: { mediaBindRequired: "Les images et vidéos nécessitent un compte APIMaster. Inscrivez-vous ou connectez-vous, puis liez Telegram.", mediaTokenRequired: "Les images et vidéos nécessitent votre propre jeton API APIMaster. Créez-en un d’abord.", mediaTopUpRequired: "Votre solde APIMaster est insuffisant. Ajoutez des fonds et réessayez.", registerAndBindButton: "S’inscrire et associer", createTokenButton: "Créer un jeton API", topUpButton: "Ajouter des fonds" },
  hi: { mediaBindRequired: "इमेज और वीडियो के लिए APIMaster खाता चाहिए। साइन अप या लॉग इन करके Telegram जोड़ें।", mediaTokenRequired: "इमेज और वीडियो के लिए आपका अपना APIMaster API Token चाहिए। पहले Token बनाएँ।", mediaTopUpRequired: "आपका APIMaster बैलेंस पर्याप्त नहीं है। धन जोड़कर फिर कोशिश करें।", registerAndBindButton: "साइन अप और कनेक्ट", createTokenButton: "API Token बनाएँ", topUpButton: "धन जोड़ें" },
  id: { mediaBindRequired: "Gambar dan video memerlukan akun APIMaster. Daftar atau masuk, lalu hubungkan Telegram.", mediaTokenRequired: "Gambar dan video memerlukan Token API APIMaster milik Anda. Buat Token terlebih dahulu.", mediaTopUpRequired: "Saldo APIMaster Anda tidak cukup. Tambahkan saldo lalu coba lagi.", registerAndBindButton: "Daftar dan hubungkan", createTokenButton: "Buat Token API", topUpButton: "Tambah saldo" },
  it: { mediaBindRequired: "Immagini e video richiedono un account APIMaster. Registrati o accedi, poi collega Telegram.", mediaTokenRequired: "Immagini e video richiedono un tuo Token API APIMaster. Creane prima uno.", mediaTopUpRequired: "Il saldo APIMaster non è sufficiente. Aggiungi fondi e riprova.", registerAndBindButton: "Registrati e collega", createTokenButton: "Crea Token API", topUpButton: "Aggiungi fondi" },
  ja: { mediaBindRequired: "画像と動画には APIMaster アカウントが必要です。登録またはログインして Telegram を連携してください。", mediaTokenRequired: "画像と動画には自分の APIMaster API Token が必要です。先に作成してください。", mediaTopUpRequired: "APIMaster の残高が不足しています。入金してもう一度お試しください。", registerAndBindButton: "登録して連携", createTokenButton: "API Token を作成", topUpButton: "入金する" },
  ko: { mediaBindRequired: "이미지와 동영상에는 APIMaster 계정이 필요합니다. 가입 또는 로그인 후 Telegram을 연결하세요.", mediaTokenRequired: "이미지와 동영상에는 본인의 APIMaster API Token이 필요합니다. 먼저 Token을 만드세요.", mediaTopUpRequired: "APIMaster 잔액이 부족합니다. 충전한 뒤 다시 시도하세요.", registerAndBindButton: "가입하고 연결", createTokenButton: "API Token 만들기", topUpButton: "잔액 충전" },
  ms: { mediaBindRequired: "Imej dan video memerlukan akaun APIMaster. Daftar atau log masuk, kemudian sambungkan Telegram.", mediaTokenRequired: "Imej dan video memerlukan Token API APIMaster anda sendiri. Cipta Token dahulu.", mediaTopUpRequired: "Baki APIMaster anda tidak mencukupi. Tambah dana dan cuba lagi.", registerAndBindButton: "Daftar dan sambung", createTokenButton: "Cipta Token API", topUpButton: "Tambah dana" },
  nl: { mediaBindRequired: "Voor afbeeldingen en video’s is een APIMaster-account nodig. Meld je aan en koppel Telegram.", mediaTokenRequired: "Voor afbeeldingen en video’s heb je een eigen APIMaster API-token nodig. Maak eerst een token.", mediaTopUpRequired: "Je APIMaster-saldo is onvoldoende. Voeg saldo toe en probeer opnieuw.", registerAndBindButton: "Registreren en koppelen", createTokenButton: "API-token maken", topUpButton: "Saldo toevoegen" },
  pl: { mediaBindRequired: "Obrazy i filmy wymagają konta APIMaster. Zarejestruj się lub zaloguj i połącz Telegram.", mediaTokenRequired: "Obrazy i filmy wymagają własnego Tokenu API APIMaster. Najpierw go utwórz.", mediaTopUpRequired: "Saldo APIMaster jest niewystarczające. Dodaj środki i spróbuj ponownie.", registerAndBindButton: "Zarejestruj i połącz", createTokenButton: "Utwórz Token API", topUpButton: "Dodaj środki" },
  pt: { mediaBindRequired: "Imagens e vídeos requerem uma conta APIMaster. Registe-se ou entre e ligue o Telegram.", mediaTokenRequired: "Imagens e vídeos requerem o seu próprio Token de API APIMaster. Crie um primeiro.", mediaTopUpRequired: "O seu saldo APIMaster é insuficiente. Adicione fundos e tente novamente.", registerAndBindButton: "Registar e ligar", createTokenButton: "Criar Token de API", topUpButton: "Adicionar fundos" },
  "pt-BR": { mediaBindRequired: "Imagens e vídeos exigem uma conta APIMaster. Cadastre-se ou entre e conecte o Telegram.", mediaTokenRequired: "Imagens e vídeos exigem seu próprio Token de API APIMaster. Crie um primeiro.", mediaTopUpRequired: "Seu saldo APIMaster é insuficiente. Adicione fundos e tente novamente.", registerAndBindButton: "Cadastrar e conectar", createTokenButton: "Criar Token de API", topUpButton: "Adicionar fundos" },
  ru: { mediaBindRequired: "Для изображений и видео нужна учётная запись APIMaster. Зарегистрируйтесь или войдите и привяжите Telegram.", mediaTokenRequired: "Для изображений и видео нужен собственный API-токен APIMaster. Сначала создайте его.", mediaTopUpRequired: "Недостаточно средств на балансе APIMaster. Пополните его и повторите попытку.", registerAndBindButton: "Регистрация и привязка", createTokenButton: "Создать API-токен", topUpButton: "Пополнить баланс" },
  th: { mediaBindRequired: "รูปภาพและวิดีโอต้องใช้บัญชี APIMaster สมัครหรือเข้าสู่ระบบแล้วเชื่อมต่อ Telegram", mediaTokenRequired: "รูปภาพและวิดีโอต้องใช้ Token API ของ APIMaster ของคุณเอง โปรดสร้าง Token ก่อน", mediaTopUpRequired: "ยอดคงเหลือ APIMaster ไม่เพียงพอ โปรดเติมเงินแล้วลองอีกครั้ง", registerAndBindButton: "สมัครและเชื่อมต่อ", createTokenButton: "สร้าง Token API", topUpButton: "เติมเงิน" },
  tr: { mediaBindRequired: "Görsel ve videolar için APIMaster hesabı gerekir. Kaydolun veya giriş yapın ve Telegram’ı bağlayın.", mediaTokenRequired: "Görsel ve videolar için kendi APIMaster API Token’ınız gerekir. Önce bir Token oluşturun.", mediaTopUpRequired: "APIMaster bakiyeniz yetersiz. Bakiye ekleyip tekrar deneyin.", registerAndBindButton: "Kaydol ve bağla", createTokenButton: "API Token oluştur", topUpButton: "Bakiye ekle" },
  uk: { mediaBindRequired: "Для зображень і відео потрібен обліковий запис APIMaster. Зареєструйтеся або увійдіть і під’єднайте Telegram.", mediaTokenRequired: "Для зображень і відео потрібен власний API-токен APIMaster. Спочатку створіть його.", mediaTopUpRequired: "На балансі APIMaster недостатньо коштів. Поповніть його та спробуйте ще раз.", registerAndBindButton: "Реєстрація і підключення", createTokenButton: "Створити API-токен", topUpButton: "Поповнити баланс" },
  uz: { mediaBindRequired: "Rasm va videolar uchun APIMaster hisobi kerak. Ro‘yxatdan o‘ting yoki kiring va Telegram’ni ulang.", mediaTokenRequired: "Rasm va videolar uchun o‘zingizning APIMaster API Tokeningiz kerak. Avval Token yarating.", mediaTopUpRequired: "APIMaster balansingiz yetarli emas. Hisobni to‘ldirib, qayta urinib ko‘ring.", registerAndBindButton: "Ro‘yxatdan o‘tish va ulash", createTokenButton: "API Token yaratish", topUpButton: "Balansni to‘ldirish" },
  vi: { mediaBindRequired: "Hình ảnh và video cần tài khoản APIMaster. Hãy đăng ký hoặc đăng nhập rồi liên kết Telegram.", mediaTokenRequired: "Hình ảnh và video cần Token API APIMaster của riêng bạn. Hãy tạo Token trước.", mediaTopUpRequired: "Số dư APIMaster không đủ. Hãy nạp thêm tiền rồi thử lại.", registerAndBindButton: "Đăng ký và liên kết", createTokenButton: "Tạo Token API", topUpButton: "Nạp tiền" },
};

type TelegramAccountButtonKey = "telegramCreateOrLoginButton" | "telegramBindExistingButton";

const TELEGRAM_ACCOUNT_TRANSLATIONS: Record<
  Exclude<BotLocale, "en" | "zh-CN" | "zh-TW">,
  Record<TelegramAccountButtonKey, string>
> = {
  ar: { telegramCreateOrLoginButton: "إنشاء حساب أو تسجيل الدخول عبر Telegram", telegramBindExistingButton: "لدي حساب APIMaster بالفعل" },
  cs: { telegramCreateOrLoginButton: "Vytvořit účet nebo se přihlásit přes Telegram", telegramBindExistingButton: "Už mám účet APIMaster" },
  de: { telegramCreateOrLoginButton: "Mit Telegram erstellen oder anmelden", telegramBindExistingButton: "Ich habe bereits ein APIMaster-Konto" },
  es: { telegramCreateOrLoginButton: "Crear cuenta o entrar con Telegram", telegramBindExistingButton: "Ya tengo una cuenta APIMaster" },
  fa: { telegramCreateOrLoginButton: "ساخت حساب یا ورود با تلگرام", telegramBindExistingButton: "از قبل حساب APIMaster دارم" },
  fr: { telegramCreateOrLoginButton: "Créer un compte ou se connecter avec Telegram", telegramBindExistingButton: "J’ai déjà un compte APIMaster" },
  hi: { telegramCreateOrLoginButton: "Telegram से बनाएँ या साइन इन करें", telegramBindExistingButton: "मेरे पास APIMaster खाता है" },
  id: { telegramCreateOrLoginButton: "Buat akun atau masuk dengan Telegram", telegramBindExistingButton: "Saya sudah punya akun APIMaster" },
  it: { telegramCreateOrLoginButton: "Crea un account o accedi con Telegram", telegramBindExistingButton: "Ho già un account APIMaster" },
  ja: { telegramCreateOrLoginButton: "Telegram で作成・ログイン", telegramBindExistingButton: "APIMaster アカウントを持っています" },
  ko: { telegramCreateOrLoginButton: "Telegram으로 만들기 또는 로그인", telegramBindExistingButton: "기존 APIMaster 계정이 있어요" },
  ms: { telegramCreateOrLoginButton: "Cipta akaun atau log masuk dengan Telegram", telegramBindExistingButton: "Saya sudah ada akaun APIMaster" },
  nl: { telegramCreateOrLoginButton: "Maken of aanmelden met Telegram", telegramBindExistingButton: "Ik heb al een APIMaster-account" },
  pl: { telegramCreateOrLoginButton: "Utwórz konto lub zaloguj się przez Telegram", telegramBindExistingButton: "Mam już konto APIMaster" },
  pt: { telegramCreateOrLoginButton: "Criar conta ou entrar com Telegram", telegramBindExistingButton: "Já tenho uma conta APIMaster" },
  "pt-BR": { telegramCreateOrLoginButton: "Criar conta ou entrar com Telegram", telegramBindExistingButton: "Já tenho uma conta APIMaster" },
  ru: { telegramCreateOrLoginButton: "Создать аккаунт или войти через Telegram", telegramBindExistingButton: "У меня уже есть аккаунт APIMaster" },
  th: { telegramCreateOrLoginButton: "สร้างบัญชีหรือเข้าสู่ระบบด้วย Telegram", telegramBindExistingButton: "ฉันมีบัญชี APIMaster อยู่แล้ว" },
  tr: { telegramCreateOrLoginButton: "Telegram ile hesap oluştur veya giriş yap", telegramBindExistingButton: "Zaten APIMaster hesabım var" },
  uk: { telegramCreateOrLoginButton: "Створити акаунт або увійти через Telegram", telegramBindExistingButton: "У мене вже є акаунт APIMaster" },
  uz: { telegramCreateOrLoginButton: "Telegram orqali yarating yoki kiring", telegramBindExistingButton: "Menda APIMaster hisobi bor" },
  vi: { telegramCreateOrLoginButton: "Tạo tài khoản hoặc đăng nhập bằng Telegram", telegramBindExistingButton: "Tôi đã có tài khoản APIMaster" },
};

const LOCALE_SET = new Set<string>(BOT_LOCALES);

export function resolveBotLocale(language?: string | null): BotLocale {
  const normalized = language?.replaceAll("_", "-").toLowerCase() ?? "";
  if (normalized.includes("hant") || /^zh-(tw|hk|mo)(-|$)/.test(normalized)) return "zh-TW";
  if (normalized.startsWith("zh")) return "zh-CN";
  if (normalized === "pt-br" || normalized.startsWith("pt-br-")) return "pt-BR";
  const base = normalized.split("-")[0] ?? "";
  return LOCALE_SET.has(base) ? base as BotLocale : "en";
}

function overrides(locale: BotLocale): MessageOverrides {
  if (locale === "zh-CN") return CHINESE_SIMPLIFIED;
  if (locale === "zh-TW") return CHINESE_TRADITIONAL;
  if (locale === "en") return {};
  return {
    ...CORE_TRANSLATIONS[locale],
    ...ACCESS_TRANSLATIONS[locale],
    ...TELEGRAM_ACCOUNT_TRANSLATIONS[locale],
    settings: SETTINGS_TRANSLATIONS[locale],
  };
}

export function botText(
  languageOrLocale: string | null | undefined,
  key: BotMessageKey,
  values: Readonly<Record<string, string | number>> = {},
): string {
  const locale = resolveBotLocale(languageOrLocale);
  const template = overrides(locale)[key] ?? ENGLISH[key];
  return template.replace(/\{([a-z_]+)\}/gi, (match, name: string) => (
    Object.hasOwn(values, name) ? String(values[name]) : match
  ));
}

export function mediaJobLocale(options: Readonly<Record<string, unknown>>, fallback?: string | null): BotLocale {
  return resolveBotLocale(typeof options.locale === "string" ? options.locale : fallback);
}
