import type { OnboardingMissingField } from "./service.js";
import { resolveBotLocale, type BotLocale } from "../telegram/localization.js";

export const ONBOARDING_ROLES = [
  "creator", "product_ops", "marketing_sales", "founder_manager",
  "developer", "designer", "education", "life_family",
] as const;

export type OnboardingRoleId = typeof ONBOARDING_ROLES[number];

interface Copy {
  roleQuestion: string;
  missingPrompt: string;
  customPrompt: string;
  roleSaved: string;
  deferred: string;
  alreadyHandled: string;
  other: string;
  later: string;
  fields: Record<OnboardingMissingField, string>;
  roles: Record<OnboardingRoleId, string>;
}

const EN: Copy = {
  roleQuestion: "By the way, I'd like to get to know you better. Which best describes your main role?",
  missingPrompt: "Got it. In one sentence, please tell me: {fields}.",
  customPrompt: "How would you describe your role? You can also tell me what to call you and what you'd most like my help with, all in one sentence.",
  roleSaved: "Got it.", deferred: "No problem. We can come back to this later.", alreadyHandled: "This choice has already been saved.",
  other: "Other", later: "Maybe later",
  fields: { preferred_name: "what I should call you", primary_role: "your main role", primary_goal: "what you'd most like my help with" },
  roles: { creator: "Content creator", product_ops: "Product / Operations", marketing_sales: "Marketing / Sales", founder_manager: "Founder / Manager", developer: "Developer", designer: "Design / Creative", education: "Student / Teacher", life_family: "Life / Family" },
};

const ZH_CN: Copy = {
  roleQuestion: "对了，想更好地认识一下你。你平时主要属于哪一类？",
  missingPrompt: "记住了。一句话告诉我就好：{fields}。",
  customPrompt: "你会怎么描述自己的角色？也可以顺便告诉我该怎么称呼你，以及最希望我帮你做什么，一句话就好。",
  roleSaved: "记住了。", deferred: "没问题，以后再聊。", alreadyHandled: "这个选择已经记录过了。", other: "其他", later: "以后再说",
  fields: { preferred_name: "以后怎么称呼你", primary_role: "你的主要角色", primary_goal: "你最希望我平时帮你做什么" },
  roles: { creator: "内容创作者", product_ops: "产品 / 运营", marketing_sales: "市场 / 销售", founder_manager: "创业者 / 管理者", developer: "开发者", designer: "设计 / 创意", education: "学生 / 教师", life_family: "生活 / 家庭" },
};

const ZH_TW: Copy = {
  roleQuestion: "對了，想更好地認識一下你。你平時主要屬於哪一類？",
  missingPrompt: "記住了。一句話告訴我就好：{fields}。",
  customPrompt: "你會怎麼描述自己的角色？也可以順便告訴我該怎麼稱呼你，以及最希望我幫你做什麼，一句話就好。",
  roleSaved: "記住了。", deferred: "沒問題，以後再聊。", alreadyHandled: "這個選擇已經記錄過了。", other: "其他", later: "以後再說",
  fields: { preferred_name: "以後怎麼稱呼你", primary_role: "你的主要角色", primary_goal: "你最希望我平時幫你做什麼" },
  roles: { creator: "內容創作者", product_ops: "產品 / 營運", marketing_sales: "市場 / 銷售", founder_manager: "創業者 / 管理者", developer: "開發者", designer: "設計 / 創意", education: "學生 / 教師", life_family: "生活 / 家庭" },
};

function localized(input: Pick<Copy, "roleQuestion" | "missingPrompt" | "customPrompt" | "deferred" | "other" | "later" | "fields" | "roles">): Copy {
  return { ...input, roleSaved: "OK", alreadyHandled: "OK" };
}

const COPIES: Record<BotLocale, Copy> = {
  en: EN, "zh-CN": ZH_CN, "zh-TW": ZH_TW,
  ar: localized({ roleQuestion: "بالمناسبة، أود أن أعرفك أكثر. ما دورك الرئيسي؟", missingPrompt: "حسنًا. أخبرني في جملة واحدة: {fields}.", customPrompt: "كيف تصف دورك؟ ويمكنك أيضًا ذكر ما أناديك به وما أهم شيء تريد مساعدتي فيه، في جملة واحدة.", deferred: "لا مشكلة، يمكننا العودة إلى هذا لاحقًا.", other: "أخرى", later: "لاحقًا", fields: { preferred_name: "ماذا أناديك", primary_role: "دورك الرئيسي", primary_goal: "أهم شيء تريد مساعدتي فيه" }, roles: { creator: "صانع محتوى", product_ops: "منتج / عمليات", marketing_sales: "تسويق / مبيعات", founder_manager: "مؤسس / مدير", developer: "مطوّر", designer: "تصميم / إبداع", education: "طالب / معلّم", life_family: "حياة / أسرة" } }),
  cs: localized({ roleQuestion: "Mimochodem, ráda bych vás lépe poznala. Jaká je vaše hlavní role?", missingPrompt: "Rozumím. Napište mi jednou větou: {fields}.", customPrompt: "Jak byste popsali svou roli? Jednou větou můžete přidat, jak vás mám oslovovat a s čím vám mám nejvíc pomáhat.", deferred: "Nevadí, můžeme se k tomu vrátit později.", other: "Jiné", later: "Možná později", fields: { preferred_name: "jak vás mám oslovovat", primary_role: "vaši hlavní roli", primary_goal: "s čím vám mám nejvíc pomáhat" }, roles: { creator: "Tvůrce obsahu", product_ops: "Produkt / Provoz", marketing_sales: "Marketing / Prodej", founder_manager: "Zakladatel / Manažer", developer: "Vývojář", designer: "Design / Kreativa", education: "Student / Učitel", life_family: "Život / Rodina" } }),
  de: localized({ roleQuestion: "Übrigens würde ich dich gern besser kennenlernen. Was ist deine Hauptrolle?", missingPrompt: "Verstanden. Sag mir in einem Satz: {fields}.", customPrompt: "Wie würdest du deine Rolle beschreiben? Sag mir gern auch in einem Satz, wie ich dich nennen soll und wobei ich dir am meisten helfen soll.", deferred: "Kein Problem, wir können später darauf zurückkommen.", other: "Sonstiges", later: "Später", fields: { preferred_name: "wie ich dich nennen soll", primary_role: "deine Hauptrolle", primary_goal: "wobei ich dir am meisten helfen soll" }, roles: { creator: "Content Creator", product_ops: "Produkt / Betrieb", marketing_sales: "Marketing / Vertrieb", founder_manager: "Gründer / Führungskraft", developer: "Entwickler", designer: "Design / Kreativ", education: "Studierende / Lehrende", life_family: "Leben / Familie" } }),
  es: localized({ roleQuestion: "Por cierto, me gustaría conocerte mejor. ¿Cuál es tu función principal?", missingPrompt: "Entendido. Dime en una frase: {fields}.", customPrompt: "¿Cómo describirías tu función? También puedes decirme cómo llamarte y en qué quieres que te ayude más, todo en una frase.", deferred: "Sin problema, podemos retomarlo más adelante.", other: "Otro", later: "Más tarde", fields: { preferred_name: "cómo debo llamarte", primary_role: "tu función principal", primary_goal: "en qué quieres que te ayude más" }, roles: { creator: "Creador de contenido", product_ops: "Producto / Operaciones", marketing_sales: "Marketing / Ventas", founder_manager: "Fundador / Responsable", developer: "Desarrollador", designer: "Diseño / Creatividad", education: "Estudiante / Docente", life_family: "Vida / Familia" } }),
  fa: localized({ roleQuestion: "راستی، دوست دارم بهتر بشناسمت. نقش اصلی‌ات چیست؟", missingPrompt: "متوجه شدم. در یک جمله بگو: {fields}.", customPrompt: "نقشت را چطور توصیف می‌کنی؟ می‌توانی در یک جمله بگویی چه صدایت کنم و بیشتر در چه کاری کمکت کنم.", deferred: "اشکالی ندارد، بعداً برمی‌گردیم.", other: "سایر", later: "بعداً", fields: { preferred_name: "چه صدایت کنم", primary_role: "نقش اصلی‌ات", primary_goal: "بیشتر در چه کاری کمکت کنم" }, roles: { creator: "تولیدکننده محتوا", product_ops: "محصول / عملیات", marketing_sales: "بازاریابی / فروش", founder_manager: "بنیان‌گذار / مدیر", developer: "توسعه‌دهنده", designer: "طراحی / خلاقیت", education: "دانشجو / مدرس", life_family: "زندگی / خانواده" } }),
  fr: localized({ roleQuestion: "Au fait, j’aimerais mieux vous connaître. Quel est votre rôle principal ?", missingPrompt: "Compris. Dites-moi en une phrase : {fields}.", customPrompt: "Comment décririez-vous votre rôle ? Vous pouvez aussi préciser comment vous appeler et ce pour quoi vous souhaitez surtout mon aide, en une phrase.", deferred: "Aucun problème, nous y reviendrons plus tard.", other: "Autre", later: "Plus tard", fields: { preferred_name: "comment vous appeler", primary_role: "votre rôle principal", primary_goal: "ce pour quoi vous souhaitez surtout mon aide" }, roles: { creator: "Créateur de contenu", product_ops: "Produit / Opérations", marketing_sales: "Marketing / Ventes", founder_manager: "Fondateur / Manager", developer: "Développeur", designer: "Design / Création", education: "Étudiant / Enseignant", life_family: "Vie / Famille" } }),
  hi: localized({ roleQuestion: "वैसे, मैं आपको बेहतर जानना चाहती हूँ। आपकी मुख्य भूमिका क्या है?", missingPrompt: "समझ गई। एक वाक्य में बताइए: {fields}।", customPrompt: "आप अपनी भूमिका कैसे बताएँगे? एक ही वाक्य में यह भी बता सकते हैं कि मैं आपको क्या कहूँ और किस काम में सबसे अधिक मदद करूँ।", deferred: "कोई बात नहीं, हम बाद में इस पर लौट सकते हैं।", other: "अन्य", later: "बाद में", fields: { preferred_name: "मैं आपको क्या कहूँ", primary_role: "आपकी मुख्य भूमिका", primary_goal: "मैं किस काम में सबसे अधिक मदद करूँ" }, roles: { creator: "कंटेंट क्रिएटर", product_ops: "प्रोडक्ट / ऑपरेशंस", marketing_sales: "मार्केटिंग / सेल्स", founder_manager: "संस्थापक / प्रबंधक", developer: "डेवलपर", designer: "डिज़ाइन / क्रिएटिव", education: "छात्र / शिक्षक", life_family: "जीवन / परिवार" } }),
  id: localized({ roleQuestion: "Ngomong-ngomong, aku ingin mengenalmu lebih baik. Apa peran utamamu?", missingPrompt: "Baik. Ceritakan dalam satu kalimat: {fields}.", customPrompt: "Bagaimana kamu menggambarkan peranmu? Kamu juga bisa menyebutkan panggilanmu dan bantuan utama yang kamu harapkan, dalam satu kalimat.", deferred: "Tidak masalah, kita bisa membahasnya nanti.", other: "Lainnya", later: "Nanti saja", fields: { preferred_name: "aku harus memanggilmu apa", primary_role: "peran utamamu", primary_goal: "bantuan utama yang kamu harapkan" }, roles: { creator: "Kreator konten", product_ops: "Produk / Operasional", marketing_sales: "Pemasaran / Penjualan", founder_manager: "Pendiri / Manajer", developer: "Developer", designer: "Desain / Kreatif", education: "Pelajar / Pengajar", life_family: "Kehidupan / Keluarga" } }),
  it: localized({ roleQuestion: "A proposito, vorrei conoscerti meglio. Qual è il tuo ruolo principale?", missingPrompt: "Capito. Dimmi in una frase: {fields}.", customPrompt: "Come descriveresti il tuo ruolo? Puoi anche dirmi come chiamarti e in cosa desideri soprattutto il mio aiuto, tutto in una frase.", deferred: "Nessun problema, ne riparleremo più avanti.", other: "Altro", later: "Più tardi", fields: { preferred_name: "come devo chiamarti", primary_role: "il tuo ruolo principale", primary_goal: "in cosa desideri soprattutto il mio aiuto" }, roles: { creator: "Creator di contenuti", product_ops: "Prodotto / Operazioni", marketing_sales: "Marketing / Vendite", founder_manager: "Fondatore / Manager", developer: "Sviluppatore", designer: "Design / Creatività", education: "Studente / Insegnante", life_family: "Vita / Famiglia" } }),
  ja: localized({ roleQuestion: "ところで、もう少しあなたのことを知りたいです。主な立場はどれですか？", missingPrompt: "わかりました。次を一文で教えてください：{fields}。", customPrompt: "ご自身の立場をどう表しますか？呼び方と、私に一番手伝ってほしいことも一文で教えてください。", deferred: "大丈夫です。また今度にしましょう。", other: "その他", later: "あとで", fields: { preferred_name: "あなたの呼び方", primary_role: "主な立場", primary_goal: "私に一番手伝ってほしいこと" }, roles: { creator: "コンテンツ制作者", product_ops: "プロダクト / 運営", marketing_sales: "マーケティング / 営業", founder_manager: "起業家 / 管理職", developer: "開発者", designer: "デザイン / クリエイティブ", education: "学生 / 教員", life_family: "生活 / 家庭" } }),
  ko: localized({ roleQuestion: "그런데, 당신을 더 잘 알고 싶어요. 주된 역할은 무엇인가요?", missingPrompt: "알겠어요. 한 문장으로 알려 주세요: {fields}.", customPrompt: "본인의 역할을 어떻게 설명하시겠어요? 제가 뭐라고 부르면 좋을지, 가장 바라는 도움도 한 문장에 함께 적어 주세요.", deferred: "괜찮아요. 나중에 다시 이야기해요.", other: "기타", later: "나중에", fields: { preferred_name: "제가 뭐라고 부를지", primary_role: "주된 역할", primary_goal: "가장 바라는 도움" }, roles: { creator: "콘텐츠 크리에이터", product_ops: "제품 / 운영", marketing_sales: "마케팅 / 영업", founder_manager: "창업자 / 관리자", developer: "개발자", designer: "디자인 / 크리에이티브", education: "학생 / 교사", life_family: "생활 / 가족" } }),
  ms: localized({ roleQuestion: "Sambil itu, saya ingin mengenali anda dengan lebih baik. Apakah peranan utama anda?", missingPrompt: "Baik. Beritahu saya dalam satu ayat: {fields}.", customPrompt: "Bagaimana anda menerangkan peranan anda? Anda juga boleh nyatakan panggilan dan bantuan utama yang diingini dalam satu ayat.", deferred: "Tiada masalah, kita boleh kembali kepadanya nanti.", other: "Lain-lain", later: "Kemudian", fields: { preferred_name: "cara saya memanggil anda", primary_role: "peranan utama anda", primary_goal: "bantuan utama yang anda inginkan" }, roles: { creator: "Pencipta kandungan", product_ops: "Produk / Operasi", marketing_sales: "Pemasaran / Jualan", founder_manager: "Pengasas / Pengurus", developer: "Pembangun", designer: "Reka bentuk / Kreatif", education: "Pelajar / Guru", life_family: "Kehidupan / Keluarga" } }),
  nl: localized({ roleQuestion: "Trouwens, ik leer je graag beter kennen. Wat is je belangrijkste rol?", missingPrompt: "Begrepen. Vertel me in één zin: {fields}.", customPrompt: "Hoe omschrijf je je rol? Vertel ook gerust in één zin hoe ik je mag noemen en waarmee je vooral hulp wilt.", deferred: "Geen probleem, we komen er later op terug.", other: "Anders", later: "Later", fields: { preferred_name: "hoe ik je mag noemen", primary_role: "je belangrijkste rol", primary_goal: "waarmee je vooral hulp wilt" }, roles: { creator: "Contentmaker", product_ops: "Product / Operatie", marketing_sales: "Marketing / Verkoop", founder_manager: "Oprichter / Manager", developer: "Ontwikkelaar", designer: "Design / Creatief", education: "Student / Docent", life_family: "Leven / Gezin" } }),
  pl: localized({ roleQuestion: "Przy okazji chcę Cię lepiej poznać. Jaka jest Twoja główna rola?", missingPrompt: "Rozumiem. Napisz w jednym zdaniu: {fields}.", customPrompt: "Jak opiszesz swoją rolę? W jednym zdaniu możesz też podać, jak mam się do Ciebie zwracać i w czym najbardziej pomagać.", deferred: "Nie ma problemu, wrócimy do tego później.", other: "Inne", later: "Później", fields: { preferred_name: "jak mam się do Ciebie zwracać", primary_role: "Twoją główną rolę", primary_goal: "w czym mam najbardziej pomagać" }, roles: { creator: "Twórca treści", product_ops: "Produkt / Operacje", marketing_sales: "Marketing / Sprzedaż", founder_manager: "Założyciel / Menedżer", developer: "Programista", designer: "Projektowanie / Kreacja", education: "Uczeń / Nauczyciel", life_family: "Życie / Rodzina" } }),
  pt: localized({ roleQuestion: "Já agora, gostaria de o conhecer melhor. Qual é a sua função principal?", missingPrompt: "Entendido. Diga-me numa frase: {fields}.", customPrompt: "Como descreveria a sua função? Pode também dizer como devo tratá-lo e em que mais deseja ajuda, tudo numa frase.", deferred: "Sem problema, voltamos a isto mais tarde.", other: "Outro", later: "Mais tarde", fields: { preferred_name: "como devo tratá-lo", primary_role: "a sua função principal", primary_goal: "em que mais deseja ajuda" }, roles: { creator: "Criador de conteúdos", product_ops: "Produto / Operações", marketing_sales: "Marketing / Vendas", founder_manager: "Fundador / Gestor", developer: "Programador", designer: "Design / Criatividade", education: "Estudante / Professor", life_family: "Vida / Família" } }),
  "pt-BR": localized({ roleQuestion: "Aliás, quero conhecer você melhor. Qual é a sua função principal?", missingPrompt: "Entendi. Conte em uma frase: {fields}.", customPrompt: "Como você descreveria sua função? Também pode dizer como devo chamar você e no que mais quer ajuda, tudo em uma frase.", deferred: "Sem problema, podemos voltar a isso depois.", other: "Outro", later: "Mais tarde", fields: { preferred_name: "como devo chamar você", primary_role: "sua função principal", primary_goal: "no que mais quer ajuda" }, roles: { creator: "Criador de conteúdo", product_ops: "Produto / Operações", marketing_sales: "Marketing / Vendas", founder_manager: "Fundador / Gestor", developer: "Desenvolvedor", designer: "Design / Criatividade", education: "Estudante / Professor", life_family: "Vida / Família" } }),
  ru: localized({ roleQuestion: "Кстати, я хотела бы узнать вас лучше. Какова ваша основная роль?", missingPrompt: "Поняла. Расскажите одним предложением: {fields}.", customPrompt: "Как бы вы описали свою роль? Одним предложением также скажите, как к вам обращаться и в чём вам больше всего нужна моя помощь.", deferred: "Без проблем, вернёмся к этому позже.", other: "Другое", later: "Позже", fields: { preferred_name: "как к вам обращаться", primary_role: "вашу основную роль", primary_goal: "в чём вам больше всего нужна моя помощь" }, roles: { creator: "Автор контента", product_ops: "Продукт / Операции", marketing_sales: "Маркетинг / Продажи", founder_manager: "Основатель / Руководитель", developer: "Разработчик", designer: "Дизайн / Творчество", education: "Студент / Преподаватель", life_family: "Жизнь / Семья" } }),
  th: localized({ roleQuestion: "ว่าแต่ ฉันอยากรู้จักคุณให้ดีขึ้น บทบาทหลักของคุณคืออะไร?", missingPrompt: "เข้าใจแล้ว บอกฉันในประโยคเดียว: {fields}", customPrompt: "คุณจะอธิบายบทบาทของตัวเองอย่างไร? บอกชื่อที่อยากให้เรียกและเรื่องที่อยากให้ช่วยที่สุดในประโยคเดียวได้เลย", deferred: "ไม่เป็นไร ไว้ค่อยคุยกันภายหลัง", other: "อื่น ๆ", later: "ไว้ทีหลัง", fields: { preferred_name: "อยากให้ฉันเรียกคุณว่าอะไร", primary_role: "บทบาทหลักของคุณ", primary_goal: "เรื่องที่อยากให้ฉันช่วยที่สุด" }, roles: { creator: "ครีเอเตอร์", product_ops: "ผลิตภัณฑ์ / ปฏิบัติการ", marketing_sales: "การตลาด / การขาย", founder_manager: "ผู้ก่อตั้ง / ผู้จัดการ", developer: "นักพัฒนา", designer: "ออกแบบ / สร้างสรรค์", education: "นักเรียน / ครู", life_family: "ชีวิต / ครอบครัว" } }),
  tr: localized({ roleQuestion: "Bu arada, sizi daha iyi tanımak isterim. Ana rolünüz nedir?", missingPrompt: "Anladım. Tek cümleyle söyleyin: {fields}.", customPrompt: "Rolünüzü nasıl tanımlarsınız? Size nasıl hitap etmemi ve en çok hangi konuda yardım istediğinizi de tek cümlede söyleyebilirsiniz.", deferred: "Sorun değil, buna daha sonra dönebiliriz.", other: "Diğer", later: "Daha sonra", fields: { preferred_name: "size nasıl hitap etmemi", primary_role: "ana rolünüzü", primary_goal: "en çok hangi konuda yardım istediğinizi" }, roles: { creator: "İçerik üreticisi", product_ops: "Ürün / Operasyon", marketing_sales: "Pazarlama / Satış", founder_manager: "Kurucu / Yönetici", developer: "Geliştirici", designer: "Tasarım / Yaratıcılık", education: "Öğrenci / Öğretmen", life_family: "Yaşam / Aile" } }),
  uk: localized({ roleQuestion: "До речі, я хотіла б краще вас пізнати. Яка ваша основна роль?", missingPrompt: "Зрозуміла. Розкажіть одним реченням: {fields}.", customPrompt: "Як би ви описали свою роль? Одним реченням також скажіть, як до вас звертатися і в чому вам найбільше потрібна моя допомога.", deferred: "Без проблем, повернемося до цього пізніше.", other: "Інше", later: "Пізніше", fields: { preferred_name: "як до вас звертатися", primary_role: "вашу основну роль", primary_goal: "у чому вам найбільше потрібна моя допомога" }, roles: { creator: "Автор контенту", product_ops: "Продукт / Операції", marketing_sales: "Маркетинг / Продажі", founder_manager: "Засновник / Керівник", developer: "Розробник", designer: "Дизайн / Творчість", education: "Студент / Викладач", life_family: "Життя / Родина" } }),
  uz: localized({ roleQuestion: "Aytgancha, sizni yaxshiroq tanimoqchiman. Asosiy rolingiz qaysi?", missingPrompt: "Tushundim. Bir jumlada ayting: {fields}.", customPrompt: "Rolingizni qanday ta’riflaysiz? Sizga qanday murojaat qilishim va eng ko‘p nimada yordam berishimni ham bir jumlada ayting.", deferred: "Muammo emas, keyinroq qaytamiz.", other: "Boshqa", later: "Keyinroq", fields: { preferred_name: "sizga qanday murojaat qilishimni", primary_role: "asosiy rolingizni", primary_goal: "eng ko‘p nimada yordam berishimni" }, roles: { creator: "Kontent yaratuvchi", product_ops: "Mahsulot / Operatsiyalar", marketing_sales: "Marketing / Savdo", founder_manager: "Asoschi / Menejer", developer: "Dasturchi", designer: "Dizayn / Ijod", education: "Talaba / O‘qituvchi", life_family: "Hayot / Oila" } }),
  vi: localized({ roleQuestion: "Nhân tiện, tôi muốn hiểu bạn hơn. Vai trò chính của bạn là gì?", missingPrompt: "Đã hiểu. Hãy nói trong một câu: {fields}.", customPrompt: "Bạn mô tả vai trò của mình thế nào? Bạn cũng có thể cho biết tôi nên gọi bạn là gì và muốn tôi hỗ trợ nhất việc gì, trong một câu.", deferred: "Không sao, chúng ta có thể nói lại sau.", other: "Khác", later: "Để sau", fields: { preferred_name: "tôi nên gọi bạn là gì", primary_role: "vai trò chính của bạn", primary_goal: "việc bạn muốn tôi hỗ trợ nhất" }, roles: { creator: "Nhà sáng tạo nội dung", product_ops: "Sản phẩm / Vận hành", marketing_sales: "Tiếp thị / Bán hàng", founder_manager: "Nhà sáng lập / Quản lý", developer: "Lập trình viên", designer: "Thiết kế / Sáng tạo", education: "Học sinh / Giáo viên", life_family: "Cuộc sống / Gia đình" } }),
};

export function onboardingCopy(language?: string | null): Copy {
  return COPIES[resolveBotLocale(language)] ?? EN;
}

export function onboardingMissingPrompt(language: string | null | undefined, missing: readonly OnboardingMissingField[]): string {
  const copy = onboardingCopy(language);
  return copy.missingPrompt.replace("{fields}", missing.map((field) => copy.fields[field]).join(", "));
}

export function onboardingRoleLabel(language: string | null | undefined, role: OnboardingRoleId): string {
  return onboardingCopy(language).roles[role];
}
